# Generated by Django 4.2.7 on 2024-02-01 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=64)),
                ('teamLeadName', models.CharField(max_length=64)),
                ('teamLeadStudentID', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 numeric characters.', regex='^[0-9]{8}$')])),
                ('teamLeadPhone', models.CharField(max_length=11)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=64)),
                ('teamLeadName', models.CharField(max_length=64)),
                ('teamLeadStudentID', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 numeric characters.', regex='^[0-9]{8}$')])),
                ('teamLeadEmail', models.EmailField(max_length=254)),
                ('teamLeadPhone', models.CharField(max_length=11)),
                ('member1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=64)),
                ('teamLeadName', models.CharField(max_length=64)),
                ('teamLeadStudentID', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 numeric characters.', regex='^[0-9]{8}$')])),
                ('teamLeadEmail', models.EmailField(max_length=254)),
                ('teamLeadPhone', models.CharField(max_length=11)),
                ('member1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoboRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=64)),
                ('teamLeadName', models.CharField(max_length=64)),
                ('teamLeadStudentID', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 numeric characters.', regex='^[0-9]{8}$')])),
                ('teamLeadEmail', models.EmailField(max_length=254)),
                ('teamLeadPhone', models.CharField(max_length=11)),
                ('member1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soccerbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=64)),
                ('teamLeadName', models.CharField(max_length=64)),
                ('teamLeadStudentID', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 numeric characters.', regex='^[0-9]{8}$')])),
                ('teamLeadEmail', models.EmailField(max_length=254)),
                ('teamLeadPhone', models.CharField(max_length=11)),
                ('member1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
