# Generated by Django 4.2.7 on 2024-02-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideagen',
            old_name='member1_name',
            new_name='member_2_name',
        ),
        migrations.RenameField(
            model_name='ideagen',
            old_name='member2_name',
            new_name='member_3_name',
        ),
        migrations.RenameField(
            model_name='ideagen',
            old_name='member3_name',
            new_name='member_4_name',
        ),
        migrations.RenameField(
            model_name='linefollow',
            old_name='member1_name',
            new_name='member_2_name',
        ),
        migrations.RenameField(
            model_name='linefollow',
            old_name='member2_name',
            new_name='member_3_name',
        ),
        migrations.RenameField(
            model_name='linefollow',
            old_name='member3_name',
            new_name='member_4_name',
        ),
        migrations.RenameField(
            model_name='roborace',
            old_name='member1_name',
            new_name='member_2_name',
        ),
        migrations.RenameField(
            model_name='roborace',
            old_name='member2_name',
            new_name='member_3_name',
        ),
        migrations.RenameField(
            model_name='roborace',
            old_name='member3_name',
            new_name='member_4_name',
        ),
        migrations.RenameField(
            model_name='soccerbot',
            old_name='member1_name',
            new_name='member_2_name',
        ),
        migrations.RenameField(
            model_name='soccerbot',
            old_name='member2_name',
            new_name='member_3_name',
        ),
        migrations.RenameField(
            model_name='soccerbot',
            old_name='member3_name',
            new_name='member_4_name',
        ),
        migrations.RemoveField(
            model_name='ideagen',
            name='member4_name',
        ),
        migrations.RemoveField(
            model_name='linefollow',
            name='member4_name',
        ),
        migrations.RemoveField(
            model_name='roborace',
            name='member4_name',
        ),
        migrations.RemoveField(
            model_name='soccerbot',
            name='member4_name',
        ),
    ]
