# Generated by Django 4.2.7 on 2024-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_chatgpt_teamleadphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideagen',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='ideagen',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='linefollow',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='linefollow',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='roborace',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='roborace',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='soccerbot',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatgpt',
            name='teamName',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='soccerbot',
            name='teamName',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
