# Generated by Django 4.2.7 on 2024-02-01 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_remove_ideagen_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideagen',
            name='member_2_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_2_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_3_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_3_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_4_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='member_4_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideagen',
            name='teamName',
            field=models.CharField(default='Default Team Name', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_2_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_2_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_3_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_3_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_4_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='member_4_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linefollow',
            name='teamName',
            field=models.CharField(default='Default Team Name', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_2_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_2_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_3_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_3_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_4_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roborace',
            name='member_4_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='roborace',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roborace',
            name='teamName',
            field=models.CharField(default='Default Team Name', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_2_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_2_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_3_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_3_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_4_Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='member_4_StudentID',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AddField(
            model_name='soccerbot',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ideagen',
            name='teamLeadEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='linefollow',
            name='teamLeadEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='roborace',
            name='teamLeadEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='soccerbot',
            name='teamLeadEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='soccerbot',
            name='teamName',
            field=models.CharField(default='Default Team Name', max_length=64, unique=True),
        ),
    ]
